services:
  - type: web
    name: fantasy-valorant
    env: python
    plan: starter          # pick "starter" or your plan in the dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JSON_DIR
        value: /opt/render/project/src/data/json   # write JSON here (persistent)
      - key: DAILY_RUN
        value: true
      - key: POLL_SECONDS
        value: "3600"                              # 1 hour; adjust if you like
      - key: TIMEZONE
        value: America/New_York
      # Set EVENT_URLS securely in the dashboard (not committed):
      # - key: EVENT_URLS
      #   sync: false
    disk:
      name: app-data
      mountPath: /opt/render/project/src/data      # persists state.sqlite + JSON
      sizeGB: 1
