agents_to_roles = {
    "Brimstone": "C",
    "Phoenix": "D",
    "Sage": "S",
    "Sova": "I",
    "Viper": "C",
    "Cypher": "S",
    "Reyna": "D",
    "Killjoy": "S",
    "Breach": "I",
    "Omen": "C",
    "Jett": "D",
    "Raze": "D",
    "Skye": "I",
    "Yoru": "D",
    "Astra": "C",
    "Kayo": "I",
    "Chamber": "S",
    "Neon": "D",
    "Fade": "I",
    "Harbor": "C",
    "Gekko": "I",
    "Deadlock": "D",
    "Clove": "C",
    "Vyse": "S",
    "Tejo": "I",
    "Waylay": "D"
}
